tag: Solve
contents:
  grounded:
    input:
      tag: DomainProblem
      domain:
        tag: PDDLDomain
        # contents: ferry.pddl
        # contents: "test-domains/d3.pddl"
        # contents: "../planner/ftb/p40-domain.pddl"
        # contents: "../planner/domains/ipc2008/seq-opt/elevators-strips/p02-domain.pddl"
        # contents: "../planner/domains/ipc2008/seq-opt/transport-strips/p02-domain.pddl"
        # contents: "../planner/domains/ipc2008/seq-opt/openstacks-strips/p02-domain.pddl"
        # contents: "../planner/primeWheels/domain.pddl"
        # contents: "../planner/domains/ipc2008/seq-opt/pegsol-strips/p07-domain.pddl"
        # contents: "../planner/domains/ipc2004/AIRPORT/NONTEMPORAL/STRIPS/P20_DOMAIN.PDDL"
        # contents: ../planner/domains/ipc2006/rovers/Propositional/domain.pddl
        # contents: ../planner/fifteenpuzzle.pddl
        contents: ../planner/crossing_domain.pddl
      problem:
        tag: PDDLProblem
        # contents: ferryprob.pddl
        # contents: "test-domains/p3.pddl"
        # contents: "../planner/ftb/p40.pddl"
        # contents: "../planner/domains/ipc2008/seq-opt/elevators-strips/p02.pddl"
        # contents: "../planner/domains/ipc2008/seq-opt/transport-strips/p02.pddl"
        # contents: "../planner/domains/ipc2008/seq-opt/openstacks-strips/p02.pddl"
        # contents: "../planner/primeWheels/wheels4.pddl"
        # contents: "../planner/domains/ipc2008/seq-opt/pegsol-strips/p07.pddl"
        # contents: "../planner/domains/ipc2004/AIRPORT/NONTEMPORAL/STRIPS/P20_AIRPORT3_P7.PDDL"
        # contents: ../planner/domains/ipc2006/rovers/Propositional/p11.pddl
        # contents: ../planner/nineprob.pddl
        contents: ../planner/crossing_prob.pddl
    mutexType: None
  solver: Stepless
