tag: Solve
contents:
  grounded:
    input:
      tag: DomainProblem
      domain:
        tag: PDDLDomain
        # contents: ../ferry.pddl
        contents: "../crossing_domain.pddl"
        # contents: "../ftb/p40-domain.pddl"
        # contents: "../domains/ipc2008/seq-opt/elevators-strips/p02-domain.pddl"
        # contents: "../domains/ipc2008/seq-opt/transport-strips/p01-domain.pddl"
        # contents: "../domains/ipc2008/seq-opt/openstacks-strips/p01-domain.pddl"
        # contents: "../primeWheels/domain.pddl"
        # contents: "../domains/ipc2008/seq-opt/pegsol-strips/p07-domain.pddl"
        # contents: "../domains/ipc2004/AIRPORT/NONTEMPORAL/STRIPS/P50_DOMAIN.PDDL"
      problem:
        tag: PDDLProblem
        # contents: ../ferryprob.pddl
        contents: "../crossing_prob.pddl"
        # contents: "../ftb/p40.pddl"
        # contents: "../domains/ipc2008/seq-opt/elevators-strips/p02.pddl"
        # contents: "../domains/ipc2008/seq-opt/transport-strips/p01.pddl"
        # contents: "../domains/ipc2008/seq-opt/openstacks-strips/p01.pddl"
        # contents: "../primeWheels/wheels4.pddl"
        # contents: "../domains/ipc2008/seq-opt/pegsol-strips/p07.pddl"
        # contents: "../domains/ipc2004/AIRPORT/NONTEMPORAL/STRIPS/P50_AIRPORT5MUC_P15.PDDL"
    mutexType: Multicliques
  solver: CostsDouble
