(define (problem strips-crossing1)
  (:domain crossing-strips)
  (:objects joe jack william averell - person)
    (:init (at joe side-a)
	   (at jack side-a)
	   (at william side-a)
	   (at averell side-a)
	   (lantern-at side-a)
	   (= (total-cost) 0)
	   (slower-than jack joe)
	   (slower-than william joe)
	   (slower-than averell joe)
	   (slower-than william jack)
	   (slower-than averell jack)
	   (slower-than averell william)
	   (= (crossing-time joe) 1)
	   (= (crossing-time jack) 2)
	   (= (crossing-time william) 5)
	   (= (crossing-time averell) 10))
  (:goal (and (at joe side-b)
	      (at jack side-b)
	      (at william side-b)
	      (at averell side-b)))
  (:metric minimize (total-cost)))
