(define (problem strips-ferry1) 
  (:domain ferry-strips)
  (:objects a b c1 c2 c3)
    (:init (place a) 
	   (place b) 
	   (car c1) 
	   (car c2)
	   (car c3)
	   (at c1 a)
	   (at c2 a)
	   (at c3 a)
	   (at-ferry a)
	   (empty-ferry))
  (:goal (and (at c1 b)
	      (at c2 b))))
