fluent(researched(bees)).
fluent(researched(cherries)).
fluent(researched(orange_crayons)).
fluent(researched(catapults)).
fluent(researched(gophers)).
fluent(researched(abacus)).
fluent(researched(combustion_engine)).
fluent(researched(banshee)).
action(research_conjunctive(bees)).
action(research_conjunctive(orange_crayons)).
action(research_conjunctive(catapults)).
action(research_conjunctive(abacus)).
action(research_conjunctive(banshee)).
action(research_disjunctive_via(cherries,bees)).
action(research_disjunctive_via(cherries,abacus)).
action(research_disjunctive_via(gophers,catapults)).
action(research_disjunctive_via(gophers,bees)).
action(research_disjunctive_via(combustion_engine,cherries)).
goal(researched(combustion_engine)).
goal(researched(banshee)).
pre(research_disjunctive_via(cherries,bees),researched(bees)).
pre(research_disjunctive_via(cherries,abacus),researched(abacus)).
pre(research_disjunctive_via(gophers,catapults),researched(catapults)).
pre(research_disjunctive_via(gophers,bees),researched(bees)).
pre(research_disjunctive_via(combustion_engine,cherries),researched(cherries)).
pre(research_conjunctive(catapults),researched(cherries)).
pre(research_conjunctive(abacus),researched(bees)).
pre(research_conjunctive(abacus),researched(orange_crayons)).
pre(research_conjunctive(abacus),researched(catapults)).
pre(research_conjunctive(banshee),researched(abacus)).
add(research_disjunctive_via(cherries,bees),researched(cherries)).
add(research_disjunctive_via(cherries,abacus),researched(cherries)).
add(research_disjunctive_via(gophers,catapults),researched(gophers)).
add(research_disjunctive_via(gophers,bees),researched(gophers)).
add(research_disjunctive_via(combustion_engine,cherries),researched(combustion_engine)).
add(research_conjunctive(bees),researched(bees)).
add(research_conjunctive(orange_crayons),researched(orange_crayons)).
add(research_conjunctive(catapults),researched(catapults)).
add(research_conjunctive(abacus),researched(abacus)).
add(research_conjunctive(banshee),researched(banshee)).
cost(research_disjunctive_via(cherries,bees),5).
cost(research_disjunctive_via(cherries,abacus),5).
cost(research_disjunctive_via(gophers,catapults),1).
cost(research_disjunctive_via(gophers,bees),1).
cost(research_disjunctive_via(combustion_engine,cherries),17).
cost(research_conjunctive(bees),5).
cost(research_conjunctive(orange_crayons),2).
cost(research_conjunctive(catapults),7).
cost(research_conjunctive(abacus),20).
cost(research_conjunctive(banshee),0).
