name:                mcp
version:             0.1.0.0
github:              "davidspies/mcp"
license:             BSD3
author:              "David Spies"
maintainer:          "dnspies@gmail.com"
copyright:           "2018 David Spies"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/davidspies/mcp#readme>

dependencies:
- base >= 4.7 && < 5
- imap
- mutex
- pddlparser
- aeson
- async
- bytestring
- clingo
- containers
- deepseq
- filepath
- mtl
- stm
- text
- wl-pprint-text
- yaml

default-extensions:
- DeriveAnyClass
- DeriveFunctor
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- GeneralizedNewtypeDeriving
- FlexibleContexts
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- ViewPatterns

ghc-options:
- -Werror
- -Wall

library:
  source-dirs: src

executables:
  mcp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mcp
