name:                pddlparser
version:             0.1.0.0
github:              "davidspies/aspplan"
license:             BSD3
author:              "David Spies"
maintainer:          "dnspies@gmail.com"
copyright:           "2018 David Spies"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/davidspies/aspplan/hworkspace/pddlparser#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- text

library:
  source-dirs: src

default-extensions:
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables

ghc-options:
- -Werror
- -Wall

executables:
  pddlparser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pddlparser

tests:
  pddlparser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pddlparser
